part of 'country_list.dart';

List<_InternalCountry> _sovereignCountries = [
  const _InternalCountry(name: 'Afghanistan', code: 'af'),
  const _InternalCountry(name: 'Albania', code: 'al'),
  const _InternalCountry(name: 'Algeria', code: 'dz'),
  const _InternalCountry(name: 'Andorra', code: 'ad'),
  const _InternalCountry(name: 'Angola', code: 'ao'),
  const _InternalCountry(name: 'Antigua and Barbuda', code: 'ag'),
  const _InternalCountry(name: 'Argentina', code: 'ar'),
  const _InternalCountry(name: 'Armenia', code: 'am'),
  const _InternalCountry(name: 'Australia', code: 'au'),
  const _InternalCountry(name: 'Austria', code: 'at'),
  const _InternalCountry(name: 'Azerbaijan', code: 'az'),
  const _InternalCountry(name: 'Bahamas', code: 'bs'),
  const _InternalCountry(name: 'Bahrain', code: 'bh'),
  const _InternalCountry(name: 'Bangladesh', code: 'bd'),
  const _InternalCountry(name: 'Barbados', code: 'bb'),
  const _InternalCountry(name: 'Belarus', code: 'by'),
  const _InternalCountry(name: 'Belgium', code: 'be'),
  const _InternalCountry(name: 'Belize', code: 'bz'),
  const _InternalCountry(name: 'Benin', code: 'bj'),
  const _InternalCountry(name: 'Bhutan', code: 'bt'),
  const _InternalCountry(name: 'Bolivia', code: 'bo'),
  const _InternalCountry(name: 'Bosnia and Herzegovina', code: 'ba'),
  const _InternalCountry(name: 'Botswana', code: 'bw'),
  const _InternalCountry(name: 'Brazil', code: 'br'),
  const _InternalCountry(name: 'Brunei', code: 'bn'),
  const _InternalCountry(name: 'Bulgaria', code: 'bg'),
  const _InternalCountry(name: 'Burkina Faso', code: 'bf'),
  const _InternalCountry(name: 'Burundi', code: 'bi'),
  const _InternalCountry(name: 'Cambodia', code: 'kh'),
  const _InternalCountry(name: 'Cameroon', code: 'cm'),
  const _InternalCountry(name: 'Canada', code: 'ca'),
  const _InternalCountry(name: 'Cape Verde', code: 'cv'),
  const _InternalCountry(name: 'Central African Republic', code: 'cf'),
  const _InternalCountry(name: 'Chad', code: 'td'),
  const _InternalCountry(name: 'Chile', code: 'cl'),
  const _InternalCountry(name: 'China', code: 'cn'),
  const _InternalCountry(name: 'Colombia', code: 'co'),
  const _InternalCountry(name: 'Comoros', code: 'km'),
  const _InternalCountry(name: 'Congo (Brazzaville)', code: 'cg'),
  const _InternalCountry(name: 'Congo (Kinshasa)', code: 'cd'),
  const _InternalCountry(name: 'Costa Rica', code: 'cr'),
  const _InternalCountry(name: 'Croatia', code: 'hr'),
  const _InternalCountry(name: 'Cuba', code: 'cu'),
  const _InternalCountry(name: 'Cyprus', code: 'cy'),
  const _InternalCountry(name: 'Czech Republic', code: 'cz'),
  const _InternalCountry(name: 'Denmark', code: 'dk'),
  const _InternalCountry(name: 'Djibouti', code: 'dj'),
  const _InternalCountry(name: 'Dominica', code: 'dm'),
  const _InternalCountry(name: 'Dominican Republic', code: 'do'),
  const _InternalCountry(name: 'Ecuador', code: 'ec'),
  const _InternalCountry(name: 'Egypt', code: 'eg'),
  const _InternalCountry(name: 'El Salvador', code: 'sv'),
  const _InternalCountry(name: 'Equatorial Guinea', code: 'gq'),
  const _InternalCountry(name: 'Eritrea', code: 'er'),
  const _InternalCountry(name: 'Estonia', code: 'ee'),
  const _InternalCountry(name: 'Eswatini', code: 'sz'),
  const _InternalCountry(name: 'Ethiopia', code: 'et'),
  const _InternalCountry(name: 'Fiji', code: 'fj'),
  const _InternalCountry(name: 'Finland', code: 'fi'),
  const _InternalCountry(name: 'France', code: 'fr'),
  const _InternalCountry(name: 'Gabon', code: 'ga'),
  const _InternalCountry(name: 'Gambia', code: 'gm'),
  const _InternalCountry(name: 'Georgia', code: 'ge'),
  const _InternalCountry(name: 'Germany', code: 'de'),
  const _InternalCountry(name: 'Ghana', code: 'gh'),
  const _InternalCountry(name: 'Greece', code: 'gr'),
  const _InternalCountry(name: 'Grenada', code: 'gd'),
  const _InternalCountry(name: 'Guatemala', code: 'gt'),
  const _InternalCountry(name: 'Guinea', code: 'gn'),
  const _InternalCountry(name: 'Guinea-Bissau', code: 'gw'),
  const _InternalCountry(name: 'Guyana', code: 'gy'),
  const _InternalCountry(name: 'Haiti', code: 'ht'),
  const _InternalCountry(name: 'Honduras', code: 'hn'),
  const _InternalCountry(name: 'Hungary', code: 'hu'),
  const _InternalCountry(name: 'Iceland', code: 'is'),
  const _InternalCountry(name: 'India', code: 'in'),
  const _InternalCountry(name: 'Indonesia', code: 'id'),
  const _InternalCountry(name: 'Iran', code: 'ir'),
  const _InternalCountry(name: 'Iraq', code: 'iq'),
  const _InternalCountry(name: 'Ireland', code: 'ie'),
  const _InternalCountry(name: 'Israel', code: 'il'),
  const _InternalCountry(name: 'Italy', code: 'it'),
  const _InternalCountry(name: 'Ivory Coast', code: 'ci'),
  const _InternalCountry(name: 'Jamaica', code: 'jm'),
  const _InternalCountry(name: 'Japan', code: 'jp'),
  const _InternalCountry(name: 'Jordan', code: 'jo'),
  const _InternalCountry(name: 'Kazakhstan', code: 'kz'),
  const _InternalCountry(name: 'Kenya', code: 'ke'),
  const _InternalCountry(name: 'Kiribati', code: 'ki'),
  const _InternalCountry(name: 'Kosovo', code: 'xk'),
  const _InternalCountry(name: 'Kuwait', code: 'kw'),
  const _InternalCountry(name: 'Kyrgyzstan', code: 'kg'),
  const _InternalCountry(name: 'Laos', code: 'la'),
  const _InternalCountry(name: 'Latvia', code: 'lv'),
  const _InternalCountry(name: 'Lebanon', code: 'lb'),
  const _InternalCountry(name: 'Lesotho', code: 'ls'),
  const _InternalCountry(name: 'Liberia', code: 'lr'),
  const _InternalCountry(name: 'Libya', code: 'ly'),
  const _InternalCountry(name: 'Liechtenstein', code: 'li'),
  const _InternalCountry(name: 'Lithuania', code: 'lt'),
  const _InternalCountry(name: 'Luxembourg', code: 'lu'),
  const _InternalCountry(name: 'Madagascar', code: 'mg'),
  const _InternalCountry(name: 'Malawi', code: 'mw'),
  const _InternalCountry(name: 'Malaysia', code: 'my'),
  const _InternalCountry(name: 'Maldives', code: 'mv'),
  const _InternalCountry(name: 'Mali', code: 'ml'),
  const _InternalCountry(name: 'Malta', code: 'mt'),
  const _InternalCountry(name: 'Marshall Islands', code: 'mh'),
  const _InternalCountry(name: 'Mauritania', code: 'mr'),
  const _InternalCountry(name: 'Mauritius', code: 'mu'),
  const _InternalCountry(name: 'Mexico', code: 'mx'),
  const _InternalCountry(name: 'Micronesia', code: 'fm'),
  const _InternalCountry(name: 'Moldova', code: 'md'),
  const _InternalCountry(name: 'Monaco', code: 'mc'),
  const _InternalCountry(name: 'Mongolia', code: 'mn'),
  const _InternalCountry(name: 'Montenegro', code: 'me'),
  const _InternalCountry(name: 'Morocco', code: 'ma'),
  const _InternalCountry(name: 'Mozambique', code: 'mz'),
  const _InternalCountry(name: 'Myanmar', code: 'mm'),
  const _InternalCountry(name: 'Namibia', code: 'na'),
  const _InternalCountry(name: 'Nauru', code: 'nr'),
  const _InternalCountry(name: 'Nepal', code: 'np'),
  const _InternalCountry(name: 'Netherlands', code: 'nl'),
  const _InternalCountry(name: 'New Zealand', code: 'nz'),
  const _InternalCountry(name: 'Nicaragua', code: 'ni'),
  const _InternalCountry(name: 'Niger', code: 'ne'),
  const _InternalCountry(name: 'Nigeria', code: 'ng'),
  const _InternalCountry(name: 'North Korea', code: 'kp'),
  const _InternalCountry(name: 'North Macedonia', code: 'mk'),
  const _InternalCountry(name: 'Norway', code: 'no'),
  const _InternalCountry(name: 'Oman', code: 'om'),
  const _InternalCountry(name: 'Pakistan', code: 'pk'),
  const _InternalCountry(name: 'Palau', code: 'pw'),
  const _InternalCountry(name: 'Palestine', code: 'ps'),
  const _InternalCountry(name: 'Panama', code: 'pa'),
  const _InternalCountry(name: 'Papua New Guinea', code: 'pg'),
  const _InternalCountry(name: 'Paraguay', code: 'py'),
  const _InternalCountry(name: 'Peru', code: 'pe'),
  const _InternalCountry(name: 'Philippines', code: 'ph'),
  const _InternalCountry(name: 'Poland', code: 'pl'),
  const _InternalCountry(name: 'Portugal', code: 'pt'),
  const _InternalCountry(name: 'Qatar', code: 'qa'),
  const _InternalCountry(name: 'Romania', code: 'ro'),
  const _InternalCountry(name: 'Russia', code: 'ru'),
  const _InternalCountry(name: 'Rwanda', code: 'rw'),
  const _InternalCountry(name: 'Saint Kitts and Nevis', code: 'kn'),
  const _InternalCountry(name: 'Saint Lucia', code: 'lc'),
  const _InternalCountry(name: 'Saint Vincent and the Grenadines', code: 'vc'),
  const _InternalCountry(name: 'Samoa', code: 'ws'),
  const _InternalCountry(name: 'San Marino', code: 'sm'),
  const _InternalCountry(name: 'Sao Tome and Principe', code: 'st'),
  const _InternalCountry(name: 'Saudi Arabia', code: 'sa'),
  const _InternalCountry(name: 'Senegal', code: 'sn'),
  const _InternalCountry(name: 'Serbia', code: 'rs'),
  const _InternalCountry(name: 'Seychelles', code: 'sc'),
  const _InternalCountry(name: 'Sierra Leone', code: 'sl'),
  const _InternalCountry(name: 'Singapore', code: 'sg'),
  const _InternalCountry(name: 'Slovakia', code: 'sk'),
  const _InternalCountry(name: 'Slovenia', code: 'si'),
  const _InternalCountry(name: 'Solomon Islands', code: 'sb'),
  const _InternalCountry(name: 'Somalia', code: 'so'),
  const _InternalCountry(name: 'South Africa', code: 'za'),
  const _InternalCountry(name: 'South Korea', code: 'kr'),
  const _InternalCountry(name: 'South Sudan', code: 'ss'),
  const _InternalCountry(name: 'Spain', code: 'es'),
  const _InternalCountry(name: 'Sri Lanka', code: 'lk'),
  const _InternalCountry(name: 'Sudan', code: 'sd'),
  const _InternalCountry(name: 'Suriname', code: 'sr'),
  const _InternalCountry(name: 'Sweden', code: 'se'),
  const _InternalCountry(name: 'Switzerland', code: 'ch'),
  const _InternalCountry(name: 'Syria', code: 'sy'),
  const _InternalCountry(name: 'Taiwan', code: 'tw'),
  const _InternalCountry(name: 'Tajikistan', code: 'tj'),
  const _InternalCountry(name: 'Tanzania', code: 'tz'),
  const _InternalCountry(name: 'Thailand', code: 'th'),
  const _InternalCountry(name: 'Timor-Leste', code: 'tl'),
  const _InternalCountry(name: 'Togo', code: 'tg'),
  const _InternalCountry(name: 'Tonga', code: 'to'),
  const _InternalCountry(name: 'Trinidad and Tobago', code: 'tt'),
  const _InternalCountry(name: 'Tunisia', code: 'tn'),
  const _InternalCountry(name: 'Turkey', code: 'tr'),
  const _InternalCountry(name: 'Turkmenistan', code: 'tm'),
  const _InternalCountry(name: 'Tuvalu', code: 'tv'),
  const _InternalCountry(name: 'Uganda', code: 'ug'),
  const _InternalCountry(name: 'Ukraine', code: 'ua'),
  const _InternalCountry(name: 'United Arab Emirates', code: 'ae'),
  const _InternalCountry(name: 'United Kingdom', code: 'gb'),
  const _InternalCountry(name: 'United States', code: 'us'),
  const _InternalCountry(name: 'Uruguay', code: 'uy'),
  const _InternalCountry(name: 'Uzbekistan', code: 'uz'),
  const _InternalCountry(name: 'Vanuatu', code: 'vu'),
  const _InternalCountry(name: 'Vatican City', code: 'va'),
  const _InternalCountry(name: 'Venezuela', code: 've'),
  const _InternalCountry(name: 'Vietnam', code: 'vn'),
  const _InternalCountry(name: 'Yemen', code: 'ye'),
  const _InternalCountry(name: 'Zambia', code: 'zm'),
  const _InternalCountry(name: 'Zimbabwe', code: 'zw'),
];